<?php
ob_start();
include_once('function.php');
$user_name=addslashes(trim($_POST['user_name']));
$phone=addslashes(trim($_POST['phone']));
$email=addslashes(trim($_POST['email']));
$mail_tag=$_POST['mail_tag'];
$email=$email.$mail_tag;
$address=addslashes(trim($_POST['address']));
$password=addslashes(trim($_POST['password']));
$password2=addslashes(trim($_POST['password2']));
$query="select 1 from user where email='$email'";
$res=mysql_query($query);
$num=mysql_num_rows($res);
if($num>0){
	alertInfo('该邮箱已被使用，请重新注册！','registe.php');
	return;
}
$password=md5($password);
$register_time=time();
$insert="insert into user(user_name,phone,email,address,password,register_time) values('$user_name','$phone','$email','$address','$password',$register_time)";
if(mysql_query($insert)){
    $flag=1;
	$newuser_id=mysql_insert_id();
	include_once('mail.php');
}
else{
	$flag=0;
	alertInfo('注册失败！','registe.php');
}
?>